name: Backend CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Spring Boot app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build Spring Boot JAR
        run: |
          cd backend/backend/backend
          mvn clean package -DskipTests
