name: Backend CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Spring Boot to ECS
    runs-on: ubuntu-latest


    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: trustscore-backend
      IMAGE_TAG: latest
      ECS_CLUSTER: trustscore-cluster
      ECS_SERVICE: trustscore-backend-service

      
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: build JAR file
        run:  ./mvnw clean package -DskipTests
      
      - name: set up docker
        uses: docker/setup-buildx-action@v3

      - name: configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push Docker image
        run: |
          IMAGE_TAG=trustscore-backend:latest
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG ${{ secrets.ECR_REGISTRY }}/$IMAGE_TAG
          docker push ${{ secrets.ECR_REGISTRY }}/$IMAGE_TAG

      - name: deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          service: trustscore-backend-service
          cluster: trustscore-cluster
          wait-for-service-stability: true
