name: Backend CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Spring Boot app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: 3.9.5

      - name: Build JAR file
        run: |
          cd backend/backend/backend
          mvn clean package -DskipTests
